### ISSUE TITLE
Wallet with imported account that has trustlines removed (due to testnet reset) keeps on spinning

### ISSUE THREAD

**Issue by gmachtel** [threefoldtech/3bot_wallet#183]
![image](https://user-images.githubusercontent.com/30384423/104741828-02235b00-574a-11eb-998c-b50309e73002.png)

Public address of the account that was cleaned up is GAESZVSPZYWRHGFQHPJZKLFPA3BSLV25G4YLM6EFOA6P4SPK5IBAMJAO . 

Trustlines have been removed but the account was already in a 3Bot wallet.

**Comment by tobiaschielens** [comment]
Account had indeed no XLM and no trustlines to tft. Removing imported wallets using dev screen doesn't work either.

**Comment by robvanmieghem** [comment]
@LeeSmet  Did you destroy(merge) the wallets during the testnet reset?

**Comment by tobiaschielens** [comment]
@LeeSmet @gmachtel  Did Import the wallet from the VDC in the wallet. Now the imported wallet has no tokens or trustlines but is still imported, leading to an infinite spinner in the wallet.

**Comment by LeeSmet** [comment]
Vdc wallets are not related to the explorer. The explorer wallets which are reset are all internal to the explorer itself. We never give out any information other than the address, so its impossible to import those

**Comment by weynandkuijpers** [comment]
I think I have the same issue - I do need access to my wallet (other account) - can this be reset?

**Comment by gmachtel** [comment]
My issue got solved by simply adding a few XLM on that account. No more spinning happened and I had access again to all accounts in the wallet.

**Comment by weynandkuijpers** [comment]
few as in 5?

**Comment by weynandkuijpers** [comment]
I funded the account I though it was but it has not fixed the issue.  I am not sure I remember which wallet (address) it was - I created a lot of eVDC's while testing.  Can you take a single account (most) recent our of my threefold connect app?

**Comment by weynandkuijpers** [comment]
Funding the account was done with a multisig wallet - other sig had thrown away the keys.  @gmachtel funded the account and isuee is solved.
